/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CraftsmanshipRouteImport } from './routes/craftsmanship'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'

const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsmanshipRoute = CraftsmanshipRouteImport.update({
  id: '/craftsmanship',
  path: '/craftsmanship',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/wholesale': typeof WholesaleRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/categories/': typeof CategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/wholesale': typeof WholesaleRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/categories': typeof CategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/wholesale': typeof WholesaleRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/categories/': typeof CategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/craftsmanship'
    | '/faq'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/story'
    | '/sustainability'
    | '/terms'
    | '/wholesale'
    | '/categories/$slug'
    | '/product/$handle'
    | '/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/craftsmanship'
    | '/faq'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/story'
    | '/sustainability'
    | '/terms'
    | '/wholesale'
    | '/categories/$slug'
    | '/product/$handle'
    | '/categories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/craftsmanship'
    | '/faq'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/story'
    | '/sustainability'
    | '/terms'
    | '/wholesale'
    | '/categories/$slug'
    | '/product/$handle'
    | '/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  CraftsmanshipRoute: typeof CraftsmanshipRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  StoryRoute: typeof StoryRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  WholesaleRoute: typeof WholesaleRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craftsmanship': {
      id: '/craftsmanship'
      path: '/craftsmanship'
      fullPath: '/craftsmanship'
      preLoaderRoute: typeof CraftsmanshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  CraftsmanshipRoute: CraftsmanshipRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  StoryRoute: StoryRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  WholesaleRoute: WholesaleRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
